name: yt-music-downloader
base: core22
version: '1.0.0'
summary: YouTube Music Downloader
description: A simple Flutter-based app for downloading YouTube Music tracks.
grade: stable
confinement: strict

apps:
  yt-music-downloader:
    command: bin/yt_music_flutter
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - network
      - network-bind
      - home
      - removable-media
      - gsettings
      - audio-playback
      - pulseaudio
    extensions:
      - gnome

parts:
  yt-music-downloader:
    plugin: dump
    source: build/linux/x64/release/bundle
    source-type: local
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libgobject-2.0-0
      - libwayland-egl1
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxkbcommon0
      - libegl1-mesa
      - libgl1-mesa-glx
      - libglu1-mesa
    organize:
      '*': bin/
    override-build: |
      craftctl default
      # Ensure executable permissions
      chmod +x $CRAFTCTL_PART_INSTALL/bin/yt_music_flutter

slots:
  yt-music-downloader:
    interface: dbus
    bus: session
    name: com.example.ytmusicdownloader