name: yt-music-downloader
base: core22
version: '1.0.0'
summary: YouTube Music Downloader
description: |
  A simple Flutter-based app for downloading YouTube Music tracks.
grade: stable
confinement: strict

apps:
  yt-music-downloader:
    command: bin/yt_music_downloader
    extensions: [gnome]
    plugs:
      - network
      - home
    desktop: yt_music_downloader.desktop

parts:
  yt-music-downloader:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
